# This is a configuration file for cargo-deny
# See https://embarkstudios.github.io/cargo-deny/

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC",
    "Zlib",
    "0BSD",
    "BSL-1.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]

[[licenses.clarify]]
crate = "adler2"
expression = "MIT OR Apache-2.0 OR 0BSD"
license-files = []

[[licenses.clarify]]
crate = "autocfg"
expression = "MIT OR Apache-2.0"
license-files = []

[[licenses.clarify]]
crate = "bincode"
expression = "MIT"
license-files = []

[[licenses.clarify]]
crate = "cfg-if"
expression = "MIT OR Apache-2.0"
license-files = []

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com"]
