name: NPM Release Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ruv-swarm/npm/**'
      - '.github/workflows/npm-release.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ruv-swarm/npm/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.6)'
        required: true
        type: string

jobs:
  test:
    name: Test NPM Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 22]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        
    - name: Setup Python with distutils (macOS)
      if: runner.os == 'macOS'
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    
    - name: Install dependencies
      working-directory: ./ruv-swarm/npm
      run: npm ci
    
    - name: Run tests
      working-directory: ./ruv-swarm/npm
      run: npm test
    
    - name: Test NPX commands
      working-directory: ./ruv-swarm/npm
      run: |
        npm link
        npx ruv-swarm --version
        npx ruv-swarm --help

  validate-wasm:
    name: Validate WASM Loading
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      working-directory: ./ruv-swarm/npm
      run: npm ci
    
    - name: Test WASM loading
      working-directory: ./ruv-swarm/npm
      run: |
        node test-wasm-loading.js
        npm run test:wasm || true

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [test, validate-wasm]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      working-directory: ./ruv-swarm/npm
      run: npm ci
    
    - name: Publish to NPM
      working-directory: ./ruv-swarm/npm
      run: |
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}